---
version: "{build}-{branch}"
image:
  - &windows Visual Studio 2017
  - &linux   Ubuntu1804
platform:
  - x64
  - x86
before_build:
  - curl -fsSL https://gist.github.com/cfillion/da355e8278048de08ae065d6fe6031c1/raw/reaper_plugin_functions.h -o vendor/reaper_plugin_functions.h
  - git submodule update --init
build_script:
  - mkdir build && cd build
  - sh:  cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmd: cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja
  - cmake --build .
for:
  - matrix: { only: [ image: *linux ] }
    install:
      - sudo apt-get update -qq
      - sudo apt-get install php -qq
      - if [ "$PLATFORM" = "x86" ]; then
          sudo apt-get install g++-multilib -qq &&
          export CFLAGS=-m32 CXXFLAGS=-m32;
        fi
    artifacts:
      - path: build/reaper_sws*.so
      - path: build/sws_python.py

  - matrix: { only: [ image: *windows ] }
    install:
      - choco install -y php
      - refreshenv
      - if "%PLATFORM%" == "x64" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
      - if "%PLATFORM%" == "x86" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
    artifacts:
      - path: build\reaper_sws*.dll
      - path: build\reaper_sws*.pdb
      - path: build\sws_python.py
