---
version: "{build}-{branch}"

build_script:
  - 'exit 1'

notifications:
  - provider: GitHubPullRequest
    on_build_failure: false
    template: |-
      {{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})
      {{#passed}}{{#jobs}}

      <details>
      <summary>{{name}}</summary>

      {{#artifacts}}
      - [{{fileName}}]({{permalink}})
      {{/artifacts}}
      </details>
      {{/jobs}}{{/passed}}
