---
version: "{build}-{branch}"
image:
  - &windows Visual Studio 2019
  - &linux   Ubuntu1804
platform:
  - x64
  - x86
before_build:
  - curl -fsSL https://gist.github.com/cfillion/da355e8278048de08ae065d6fe6031c1/raw/reaper_plugin_functions.h -o vendor/reaper_plugin_functions.h
  - git submodule update --init
build_script:
  - mkdir build && cd build
  - sh:  cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmd: cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja
  - cmake --build . --target all langpack
  - cpack
for:
  - matrix: { only: [ image: *linux ] }
    install:
      - sudo apt-get update -qq
      - sudo apt-get install php -qq
      - if [ "$PLATFORM" = "x86" ]; then
          sudo apt-get install g++-multilib -qq &&
          export CFLAGS=-m32 CXXFLAGS=-m32;
        fi
    artifacts:
      - path: build/sws*.tar.xz
      - path: build/reaper_sws*.so
      - path: build/sws_python*.py
      - path: build/BuildUtils/SWS_Template.ReaperLangPack

  - matrix: { only: [ image: *windows ] }
    install:
      - choco install -y nsis php
      - refreshenv
      - curl -fsSLO https://nsis.sourceforge.io/mediawiki/images/3/3c/FindProc.zip
      - 7z e FindProc.zip -o"%ProgramFiles(x86)%\NSIS\Plugins\x86-unicode" FindProcDLL.dll

      - if "%PLATFORM%" == "x64" call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
      - if "%PLATFORM%" == "x86" call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
    artifacts:
      - path: build\sws*.exe
      - path: build\reaper_sws*.dll
      - path: build\reaper_sws*.pdb
      - path: build\sws_python*.py
      - path: build\BuildUtils\SWS_Template.ReaperLangPack
